### ISSUE TITLE
SourceKittenDaemon is not killed by sending request for `/stop`

### ISSUE THREAD

**Issue by mitsuse** [terhechte/SourceKittenDaemon#35]
I tried to stop SourceKittenDaemon by executing `http get http://localhost:8081/stop`.
The connection is closed but the process of SourceKIttenDaemon is still alive.

Is this a bug or correct behavior to change the project without restarting server?

**Comment by nathankot** [comment]
Hmmm will probably have to patch Taylor: https://github.com/izqui/Taylor/blob/9b441bb7829d46d40060a251990eef1b3b38845c/Sources/Taylor/Taylor.swift#L58-L64

**Comment by nathankot** [comment]
Actually, might be better to just stop the server but keep the daemon running until another query is made or just remove that endpoint completely.

**Comment by terhechte** [comment]
I spend some time trying out various lightweight Swift web servers which also include Linux support for (maybe) future additions and less dependencies. However, due to the Swift2 / Swift 3 switch, that's currently a bit difficult as the interesting ones are all Swift 3. So for now I'd say we remove the "/stop" endpoint until Swift 3 hits and we can switch to an easier web server.
@nathankot Would you agree?

**Comment by nathankot** [comment]
@terhechte yup I agree to switching to a nicer server library :) which libraries are you talking about specifically? Haven't played with Swift 3 yet.

Although I don't see us re-implementing `/stop` even with the new library since I feel like the stopping/killing of a daemon should not be possible via it's API.

**Comment by terhechte** [comment]
@nathankot My current favourite is this one: https://github.com/kylef/Curassow However I'm not sure I checked everything.

**Comment by nathankot** [comment]
Looks like a lot of options can be found on https://github.com/nestproject/Nest :)
